name: freshpantry
region: lon
services:
  - name: web
    dockerfile_path: Dockerfile
    github:
      repo: jistjad-star/freshpantry
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    envs:
      - key: MONGO_URL
        scope: RUN_TIME
        type: SECRET
      - key: DB_NAME
        scope: RUN_TIME
        value: freshpantry
      - key: EMERGENT_LLM_KEY
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: "*"
      - key: REACT_APP_BACKEND_URL
        scope: BUILD_TIME
        value: ""
    routes:
      - path: /
